on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: example-application
      - name: Initialize
        working-directory: example-application
        run: |
          west init -l .
          west update
      # TODO(mskobov): Use imgtool to sign the existing binary instead
      # TODO(mskobov): Automatically push to S3
      - name: Build signed firmware
        working-directory: example-application
        run: |
          west build -b stm32l496_cell app -p -- -DCONFIG_MCUBOOT_SIGNATURE_KEY_FILE=\"example-application/conf/root-rsa-2048.pem\" -DEXTRA_CONF_FILE=mcumgr.conf
      - name: Copy signed firmware
        run: |
          cp example-application/build/zephyr/zephyr.signed.bin ${{ github.sha }}.signed.bin
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.sha }}-signed.bin
